spring:
  datasource:
    url: jdbc:mysql://localhost:3307/dbspotmusic?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
      show_sql: true
      hbm2ddl:
      auto: update